### ISSUE TITLE
Emerald-tier teleporter somehow teleports to gold tier teleporter on a different frequency 1000+ blocks away?

### ISSUE THREAD

**Issue by IAmEchino** [SmoochyPit/Warp-Pads#4]
Hey SmoochyPit! I've been using your datapack on my Minecraft server for quite a few months now, and I just recently experienced my first major bug (aside from that private teleporter issue you fixed in the most recent update). 

On my server (running PaperMC), I had an emerald-tier teleporter randomly start intermittently teleporting players to the wrong pad. Instead of going to the pad named "Exavia" (my base), it teleported players to a gold-tier teleporter over 1000 blocks away that was on a different frequency (the emerald teleporter was on the default, the gold was on frequency 2). 

This is a problem for my server because we're having a bit of a war and that gold teleporter allowed me to see one of the enemy's secret bases. 

Unfortunately I can't really attach the world file here (it's gigabytes in size), but if you would like to come onto my server to see the issue for yourself, I would be happy to oblige. I just need your MC username so I can whitelist you.

I hope I can help you squash this bug!

Echino

**Comment by SmoochyPit** [comment]
That's quite a problem! Yeah, I'd love to take a look at that. I use a temporary ID system to link the warp pad and the corresponding marker, so I bet that is getting messed up somewhere along the way. Would you be able to add me on Discord so we can further investigate this? @SmoochyPit#8036

**Comment by SmoochyPit** [comment]
I haven't heard back from you and I am unable to replicate this issue. I'm closing it for now.

**Comment by IAmEchino** [comment]
Understandable, thanks anyways. : )
