### ISSUE TITLE
Sneak Toggle Triggers Anti-Spam

### ISSUE THREAD

**Issue by inventor200** [SmoochyPit/Warp-Pads#7]
If a player has sneak set to toggle for accessibility settings, using a warp pad instantly triggers the anti-spam mechanism.

**Comment by SmoochyPit** [comment]
https://github.com/SmoochyPit/Warp-Pads-Rewrite/issues/2

Affects >=v2.0; I made an issue on that repo and it can be found [here](https://github.com/SmoochyPit/Warp-Pads-Rewrite/issues/2).
